{% set name = "mpackview" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mpackview-{{ version }}.tar.gz
  sha256: 4ceed7b98800f4e956b0834275b5bbabad98995f7d827ae891926e2d427169e4

build:
  entry_points:
    - mpackview = mpackview:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - aiofiles >=0.7.0
    - asyncqt >=0.8
    - matplotlib-base >=3.5
    - mpacklog >=3.1.0
    - msgpack-python >=1.0.2
    - pyside2 >=5.11.0
    - qtpy >=2.0.1

test:
  imports:
    - mpackview
  commands:
    - pip check
    - mpackview --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: GUI to stream MessagePack log files.
  dev_url: https://github.com/upkie/mpacklog.py
  license: Apache-2.0
  license_file: LICENSE
  home: https://pypi.org/project/mpackview/

extra:
  recipe-maintainers:
    - stephane-caron
